package html4k

import html4k.*

/*******************************************************************************
    DO NOT EDIT
    This file was generated by module generate
*******************************************************************************/

public fun <T, C : TagConsumer<T>> C.div(classes : String? = null, block : DIV.() -> Unit) : T = build(listOf("class" to classes).toAttributesMap(), ::buildDIV, block).finalize()

public fun <T, C : TagConsumer<T>> C.p(block : P.() -> Unit) : T = build(emptyMap(), ::buildP, block).finalize()

public fun <T, C : TagConsumer<T>> C.head(block : HEAD.() -> Unit) : T = build(emptyMap(), ::buildHEAD, block).finalize()

public fun <T, C : TagConsumer<T>> C.a(href : String? = null, target : Targets? = null, block : A.() -> Unit) : T = build(listOf("href" to href,"target" to target?.enumEncode()).toAttributesMap(), ::buildA, block).finalize()

public fun <T, C : TagConsumer<T>> C.html(block : HTML.() -> Unit) : T = build(emptyMap(), ::buildHTML, block).finalize()

public fun <T, C : TagConsumer<T>> C.body(block : BODY.() -> Unit) : T = build(emptyMap(), ::buildBODY, block).finalize()

public fun <T, C : TagConsumer<T>> C.title(content : String = "") : T = build(emptyMap(), ::buildTITLE, {+content}).finalize()

public fun <T, C : TagConsumer<T>> C.span(block : SPAN.() -> Unit) : T = build(emptyMap(), ::buildSPAN, block).finalize()

