package html4k

import html4k.*
import html4k.impl.*

/*******************************************************************************
    DO NOT EDIT
    This file was generated by module generate
*******************************************************************************/

fun buildDIV(attributes : Map<String, String>, consumer : TagConsumer<*>, block : DIV.() -> Unit) : Unit = DIV(attributes, consumer).visit(block)
fun buildP(attributes : Map<String, String>, consumer : TagConsumer<*>, block : P.() -> Unit) : Unit = P(attributes, consumer).visit(block)
fun buildHEAD(attributes : Map<String, String>, consumer : TagConsumer<*>, block : HEAD.() -> Unit) : Unit = HEAD(attributes, consumer).visit(block)
fun buildA(attributes : Map<String, String>, consumer : TagConsumer<*>, block : A.() -> Unit) : Unit = A(attributes, consumer).visit(block)
fun buildHTML(attributes : Map<String, String>, consumer : TagConsumer<*>, block : HTML.() -> Unit) : Unit = HTML(attributes, consumer).visit(block)
fun buildBODY(attributes : Map<String, String>, consumer : TagConsumer<*>, block : BODY.() -> Unit) : Unit = BODY(attributes, consumer).visit(block)
fun buildTITLE(attributes : Map<String, String>, consumer : TagConsumer<*>, block : TITLE.() -> Unit) : Unit = TITLE(attributes, consumer).visit(block)
fun buildSPAN(attributes : Map<String, String>, consumer : TagConsumer<*>, block : SPAN.() -> Unit) : Unit = SPAN(attributes, consumer).visit(block)
