package html4k

import html4k.*

/*******************************************************************************
    DO NOT EDIT
    This file was generated by module generate
*******************************************************************************/

enum public class Targets(override val realValue : String) : AttributeEnum {
    blank : Targets("_blank")
    self : Targets("_self")
    parent : Targets("_parent")
    top : Targets("_top")
}

val targetsValues : Map<String, Targets> = Targets.values().toMap { it.name() }

